# -*- coding: utf-8 -*-
"""Airbnb Listing Analysis for Optimal Pricing and Availability Template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TcOuwbfAGlv9Z-9cU59ZchgFWEYDhjI9

# **Project Name**:   Airbnb Listing Analysis for Optimal Pricing and Availability

##### **Project Type**    - EDA
##### **Contribution**    - Individual

# **Project Summary -**

Write the summary here within 500-600 words.

The Airbnb platform has revolutionized the hospitality industry by enabling property owners to offer short-term rentals to travelers around the world. However, many Airbnb hosts encounter challenges when it comes to pricing their properties competitively, ensuring high occupancy rates, and delivering a high level of guest satisfaction. With the rapid growth of listings, the competition has become intense, making it essential for hosts to leverage data-driven insights to stand out in the market. This project aims to analyze a dataset containing detailed information about Airbnb listings, with a focus on identifying trends and patterns that can help hosts make informed decisions to optimize their rental properties.

The dataset includes columns such as id, name, host_id, host_name, neighbourhood_group, neighbourhood, latitude, longitude, room_type, price, minimum_nights, number_of_reviews, last_review, reviews_per_month, calculated_host_listings_count, and availability_365. Each of these columns provides valuable information about the listings, from geographical location and host details to pricing, reviews, and availability throughout the year. This diversity in the data allows for a comprehensive analysis that can be used to generate actionable insights for hosts.

The first focus area of the analysis is pricing optimization. Pricing is a crucial factor that directly impacts both the host's revenue and the guest's decision to book a property. By analyzing the relationship between room_type, neighbourhood, and price, we aim to identify pricing patterns that lead to higher booking rates. For example, certain room types or locations may command a premium price due to their proximity to tourist attractions or business districts. Additionally, analyzing the price column alongside reviews_per_month can reveal how guest satisfaction and reviews affect a host's ability to charge higher rates. These insights can guide hosts in setting competitive prices that align with market demand while maximizing their revenue potential.

Occupancy rates are another critical area of analysis. The minimum_nights and availability_365 columns provide information about the booking policies set by hosts and the availability of their properties throughout the year. By examining how different minimum night requirements and the frequency of availability impact booking rates, the analysis aims to provide recommendations for optimizing these parameters. For instance, listings with lower minimum night requirements may attract more short-term travelers, leading to higher overall occupancy. Understanding these trends can help hosts adjust their settings to better cater to market preferences, ensuring a more consistent stream of bookings.

# **GitHub Link -**

Provide your GitHub Link here.
https://github.com/Vivek2292kumar

# **Problem Statement**

**Write Problem Statement Here.**  
Airbnb hosts face challenges in setting optimal prices and ensuring a high occupancy rate while maintaining a positive guest experience. Understanding how different factors such as location, room type, and host activity levels impact listing performance is crucial for hosts to remain competitive in the market. Without data-driven insights, hosts risk setting prices too high or low, leading to reduced revenue or underutilized properties. This project aims to analyze these factors to identify patterns and provide recommendations for hosts to improve their listing performance.

#### **Define Your Business Objective?**

The business objective of this project is to empower Airbnb hosts with data-driven insights to enhance their listing performance. By analyzing factors like pricing, occupancy, customer satisfaction, and geographic trends, the project aims to help hosts set optimal prices, improve occupancy rates, and enhance guest experiences. These insights will enable hosts to make strategic adjustments to their pricing models, availability settings, and service quality. Ultimately, the goal is to maximize hosts' revenue potential, maintain a competitive edge in the market, and create a positive experience for guests, driving sustained success in the short-term rental market.Answer Here.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

"""### Dataset Loading"""

# Load Dataset
from google.colab import drive
drive.mount('/content/drive')

os.chdir('/content/drive/MyDrive/Module 2  documents')
!ls
df = pd.read_csv('Airbnb NYC 2019.csv')

"""### Dataset First View"""

# Dataset First Look
df.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
df.shape

"""### Dataset Information"""

# Dataset Info
df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
df.duplicated().sum()

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
df.isnull().sum()

# Visualizing the missing values
sns.heatmap(data = df.isnull(), cbar =  False)

"""### What did you know about your dataset?

Answer Here   From the above data set we can seen missing vales , duplicated values and more ....
**Chage data_type**
last review column need change datatype from object to datetime
**Missing value**
somme columns need missing value imputation like..
name host_id , last_review , review_per month
**Duplicated values**
as we can there is no duplicated value in  the dataset

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df.columns

# Dataset Describe
df.describe()

"""### Variables Description

*Answer*

**id** : Unique identifier for each listing and property

**name**:  Name or title of the listing, typically provided by the host.

**host_id**: Unique identifier for the host who manages the listing.

**host_name**: Name of the host managing the listing.

**neighbourhood_group**: Broad area or borough where the listing is located (e.g., Manhattan, Brooklyn).

**neighbourhood**: Specific neighborhood within the neighbourhood_group where the listing is located.

**latitude**: Latitude coordinate of the listing’s location, used for mapping.

**longitude**: Longitude coordinate of the listing’s location, used for mapping.

**room_type**: Type of room being offered (e.g., Entire home/apt, Private room, Shared room).

**price**: Price per night for the listing, in the local currency (e.g., USD).

**minimum_nights**: Minimum number of nights required for a booking.

**number_of_reviews**: Total number of reviews received by the listing.

**last_review**: Date of the most recent review for the listing.

**reviews_per_month**: Average number of reviews the listing receives per month.

**calculated_host_listings_count**: Total number of listings the host manages, reflecting their hosting experience.

**availability_365**: Number of days the listing is available for booking in a year (365 days).
"""



"""### Check Unique Values for each variable."""

# Check Unique Values for each variable.
df.nunique()

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
# chnge 'last_review' column to datetime from object
df['last_review'] = pd.to_datetime(df['last_review'])
# impute missing value
# impute missing values with 0 in columns like
df['last_review'] = df['last_review'].fillna(df['last_review'].max())
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)
# remove unnecesarry columns
df.drop(['name','host_name'] , axis = 1 , inplace = True)

# check  the dataset again
df.info(), df.isnull().sum() , df.duplicated().sum()

"""### What all manipulations have you done and insights you found?

```
# This is formatted as code
```

Answer Here. First we convert datatype of lasr_review column to make it analyse from object type to datetime formate, fill missing value in the column with the last review date , fill missing value of 'reviews_per_month' with  0 , remove unnecessary columns from the data set who all are unuseful for the analysis like ; 'name' , 'host_name'

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 visualization code
#room_type vs price
plt.figure(figsize=(8, 6))
sns.barplot(x='room_type', y='price', data=df, estimator=lambda x: sum(x) / len(x))
plt.title('Average Price by Room Type')
plt.xticks(rotation=45)
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here. i pick the bar chact to visulize and comapre the room_type booking with the price

##### 2. What is/are the insight(s) found from the chart?

Answer Here As we can see in the chart entire home/apt have more bookings as compared to others 2 room types

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here. this helps in  hosts optimize their pricing strategies. For example, if "Entire home/apt" has a higher average price, hosts can set competitive rates based on this benchmark to attract more guests while maximizing revenue.

#### Chart - 2
"""

# Chart - 2 visualization code
#neighbourhood_group vs number_of_reviews
plt.figure(figsize=(8, 6))
sns.barplot(x='neighbourhood_group', y='number_of_reviews', data=df, estimator=lambda x: sum(x))
plt.title('Total Number of Reviews by Neighbourhood Group')
plt.xticks(rotation=45)
plt.show()

"""##### 1. Why did you pick the specific chart?

```
# This is formatted as code
```

Answer Here. we choose this chart to comapre and visulize which neighbourhood_group have more feedback as comapre to others

##### 2. What is/are the insight(s) found from the chart?

Answer Here  As we can see from the chart Brooklyn  have more more feedback as come to others

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here  thsi helps in focus marketing and promotional efforts on high-demand neighborhoods to attract more bookings. Hosts can also invest in improving properties in popular areas to capitalize on demand.

#### Chart - 3
"""

# Chart - 3 visualization code
plt.figure(figsize=(8, 6))
sns.histplot(df['price'], bins=30, kde=True)
plt.title('Distribution of Prices')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.  To understand the range and  distribution of price.

##### 2. What is/are the insight(s) found from the chart?

Answer Here. AS we can see in the data most of the price distributed between 0 to 2000

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here. Hosts can price their listings within popular ranges to increase booking likelihood. Understanding the distribution helps avoid overpricing or underpricing.

#### Chart - 4
"""

# Chart - 4 visualization code
# 4. Histogram: minimum_nights
plt.figure(figsize=(8, 6))
sns.histplot(df['minimum_nights'], bins=30, kde=True)
plt.title('Distribution of Minimum Nights')
plt.xlabel('Minimum Nights')
plt.ylabel('Frequency')
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here. we choose this chart chaeck and visualize the frewunct of the night- stayed  in the hotel

##### 2. What is/are the insight(s) found from the chart?

Answer Here.As we can see from the given data minimum number of nights are stayed between 0 to 200

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here Helps in adjusting the minimum stay to match market demand. If shorter stays are more common, adjusting policies could increase bookings.

#### Chart - 5
"""

# Chart - 5 visualization code
# 5. Pie Chart: room_type
plt.figure(figsize=(8, 6))
df['room_type'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90)
plt.title('Proportion of Room Types')
plt.ylabel('')
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here. we use this chart to check the proportion of which room_type have more have more number of booking as compared to other room types

##### 2. What is/are the insight(s) found from the chart?

Answer Here. As we can see from the above figure that nost of the booking  from the entire home/apt as compared to others and private rooms are bit less then entirehome/apt

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here  Helps hosts identify underserved room types and consider offering them. For example, if "Private rooms" are less common but in demand, adding such listings could fill a market gap.

#### Chart - 6
"""

# Chart - 6 visualization code
# 6. Pie Chart: neighbourhood_group
plt.figure(figsize=(8, 6))
df['neighbourhood_group'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90)
plt.title('Proportion of Listings by Neighbourhood Group')
plt.ylabel('')
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here. we use this specific chart to see the market share and each neighbourhood group

##### 2. What is/are the insight(s) found from the chart?

Answer Here  As we can see from the above chart most of the listing are from Manhattan and then from Brooklyn

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here. Helps hosts understand competition levels in various neighborhoods and identify potential areas for expansion where fewer listings may mean lower competition.

#### Chart - 7
"""

# Chart - 7 visualization code
# 7. Box Plot: neighbourhood_group vs price
plt.figure(figsize=(10, 6))
sns.boxplot(x='neighbourhood_group', y='price', data=df)
plt.title('Price Distribution by Neighbourhood Group')
plt.xticks(rotation=45)
plt.ylim(0, 500)  # Adjust as needed to exclude extreme outliers
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here. we use this chart to To visualize price distributions across neighborhoods and identify outliers.

##### 2. What is/are the insight(s) found from the chart?

Answer Here. we can see from the chart Manhanttan neighbourhood_group have higher prive variation and low outliers , Queens neighbourhood_group have low prive variation and higher outliers and Bronx have higher outliers and low price variation

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here. Helps in setting realistic prices for properties based on neighborhood trends, which can lead to better pricing strategies and increased bookings.

#### Chart - 8
"""

# Chart - 8 visualization code
# 8. Box Plot: room_type vs price
plt.figure(figsize=(8, 6))
sns.boxplot(x='room_type', y='price', data=df)
plt.title('Price Distribution by Room Type')
plt.ylim(0, 500)  # Adjust as needed to exclude extreme outliers
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here. To analyze price variations within each room type.

##### 2. What is/are the insight(s) found from the chart?

Answer Here As we can see Private room have low price variation and higher outliers , Entire home/apt have mediaum price variation and lower outliers , Shared  room type have low price variation and hiegher outliers

> Add blockquote

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here  Helps hosts understand how much they can potentially charge for each room type and adjust pricing to remain competitive while maximizing revenue.

#### Chart - 9
"""

# Chart - 9 visualization code
plt.figure(figsize=(8, 6))
sns.scatterplot(x='longitude', y='latitude', data=df, hue='neighbourhood_group', alpha=0.6)
plt.title('Geographical Distribution of Listings')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.legend(title='Neighbourhood Group')
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.  i use this chart to visualize the  geographical distribution of listings

##### 2. What is/are the insight(s) found from the chart?

Answer Here
AS we can see from the chart that most of the listings are from Brooklyn and Manhattan  and in  the  mid of the latitude and longitude

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here
Helps identify underserved or over-saturated areas, guiding decisions on where to list new properties or focus marketing efforts to attract guests to less saturated areas

#### Chart - 10
"""

# Chart - 10 visualization code
# 10. Scatter Plot: price vs number_of_reviews
plt.figure(figsize=(8, 6))
sns.scatterplot(x='price', y='number_of_reviews', data=df, alpha=0.6)
plt.title('Price vs Number of Reviews')
plt.xlabel('Price')
plt.ylabel('Number of Reviews')
plt.xlim(0, 500)  # Adjust as needed to focus on main data
plt.ylim(0, 300)  # Adjust as needed to focus on main data
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.
we use this chart to check the distribution of  price and number of reviews
with the help of scatter plot

##### 2. What is/are the insight(s) found from the chart?

Answer Here
As we can see in the figure more listigs are from the price 0 to 200  as lower price have more number of reviews and hiegher price have low numbers of reviews

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here
 Helps in setting the right price that balances attracting more reviews and maintaining profitability, which can enhance listing visibility and trustworthiness.

#### Chart - 11
"""

# Chart - 11 visualization code
#last_review vs number_of_reviews
#df['last_review'] = pd.to_datetime(df['last_review'])
df.set_index('last_review', inplace=True)
df['number_of_reviews'].resample('M').sum().plot(figsize=(10, 6))
plt.title('Monthly Total Number of Reviews')
plt.xlabel('Month')
plt.ylabel('Number of Reviews')
plt.show()
df.reset_index(inplace=True)

"""##### 1. Why did you pick the specific chart?

Answer Here.
i use this chart to see and visulize which year have maximumin number of reviews and with year have minumum number of reviews

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 12
"""

# Chart - 12 visualization code
plt.figure(figsize=(8, 6))
sns.lineplot(x='availability_365', y='price', data=df)
plt.title('Availability (365 Days) vs Price')
plt.xlabel('Availability (Days)')
plt.ylabel('Price')
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.
To see how listing prices correlate with their availability throughout the year.

##### 2. What is/are the insight(s) found from the chart?

Answer Here
 we can see from the chart some sharp increases in prices around 150, 200, and 250 days, which means some hosts set higher prices, probably aiming for guests who are willing to pay more. When listings are available for 365 days, their prices tend to stay more stable. This means that hosts who keep their listings open all year could adjust their prices during times when bookings are slow to attract more guests and make more money.








> Add blockquote

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

 Helps in understanding how to adjust pricing to either increase occupancy or maintain exclusivity for higher rates, maximizing revenue throughout the year.

#### Chart - 13
"""

# Chart - 13 visualization code
# 13. Count Plot: calculated_host_listings_count
plt.figure(figsize=(8, 6))
sns.countplot(x='calculated_host_listings_count', data=df)
plt.title('Count of Host Listings')
plt.xlabel('Number of Listings by Host')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here. we use this chart to visualize the distribution of the number of listings managed by hosts.

##### 2. What is/are the insight(s) found from the chart?

Answer Here
 As we can see from the chart 1 has higher number of count , 2 has less than 1  , 3 has more less than 2 simillarly till 327 count is constant

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here
Identifies opportunities for hosts with a few listings to scale their portfolio and helps new hosts understand typical hosting patterns in the market.

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
plt.figure(figsize=(10, 8))
sns.heatmap(df[['price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month',
                'calculated_host_listings_count', 'availability_365']].corr(),
            annot=True, cmap='coolwarm', center=0)
plt.title('Correlation Heatmap')
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.
we use this chart to identify the relation between the  numerical variables.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

we can see from the  chart ,reviews per month and number of reviews have a strong positive correlation (0.59), meaning that properties with more reviews tend to get reviewed more frequently. Availability_365 also has a moderate positive correlation with calculated_host_listings_count (0.23), suggesting that hosts with more listings tend to keep their properties available for longer periods.

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code
sns.pairplot(df[['price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month',
                 'calculated_host_listings_count', 'availability_365']])
plt.suptitle('Pair Plot of Numerical Variables', y=1.02)
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.
we use this spefic chart to  visualize pairwise relationships between multiple numerical variables.

##### 2. What is/are the insight(s) found from the chart?

Answer Here
 we can see from the chart, price is widely spread but mostly concentrated at lower values. Number of reviews tends to be higher for listings with lower prices. Availability_365 is generally consistent, but some listings have very low availability.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

Answer Here.

**Adjust Pricing Based on Demand**: we can set competitive prices.Like  if lower prices attract more reviews and bookings, consider adjusting prices during off-peak times to increase occupancy.

**Optimize Availability Settings**: If  listings with low availability but high demand, consider increasing availability to maximize bookings. Keeping properties open throughout the year can attract more guests and generate more revenue.

**Encourage Guest Reviews**: Properties with more reviews attract more bookings. Encourage guests to leave reviews by providing a good experience, offering small incentives, or following up with them after their stay.

**Expand Portfolio Strategically**: Hosts with multiple listings tend to have higher availability and consistent bookings. Consider adding more properties in high-demand areas or those with fewer competitors to scale up and improve profitability.
"""



"""# **Conclusion**

Write the conclusion here.
In this project, the analysis of Airbnb listing data reveals key insights that can help hosts optimize their pricing, availability, and overall strategy. Understanding the relationship between price and availability allows hosts to adjust their rates to attract more bookings or maintain exclusivity. The positive correlation between the number of reviews and review frequency highlights the importance of guest feedback in attracting new bookings. By strategically setting prices, keeping properties available, encouraging guest reviews, and considering expansion opportunities, hosts can maximize their revenue, improve occupancy rates, and provide better experiences for guests, achieving long-term success in the competitive Airbnb market.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""